== Introduction

This repository hosts the lab guide for the OpenShift on OpenShift with Hosted Control Planes lab, which will be delivered by Red Hat Associates at the Red Hat One event in Spring 2025.

It is designed to work with the Showroom lab environment provided by the Red Hat Demo Platform (RHDP) team.

This lab is organized to allow you to have a hands-on experience with Red Hat OpenShift Virtualization.

OpenShift Virtualization enables you to bring virtual machines onto a modern, Kubernetes-based infrastructure. It enables the development and delivery of new applications as well as the modernization of existing ones and can create applications that consist of virtual machines, containers, and serverless functions - all managed together using Kubernetes-native tools and paradigms.

In this event we will explore many common management activities that virtual administrators often encounter in their day to day workflows.


== Lab Content

These are the four main sections that will be covered:

*Deployment:* Using Red Hat Advanced Cluster Management for Kubernetes (RHACM) to deploy a virtual OpenShift on OpenShift cluster using Red Hat OpenShift Virtualization. This section also explores the environment once it's deployed.

*Configuration:* Performing operations on the *hosting* cluster to enact configuration changes on the *hosted* cluster. 

*Scaling:* NodePools in a Hosted Control Planes environment can be configured to autoscale when resources are unavaialable to meet application requests. We will deploy an application and scale it up, requiring the cluster to scale up dynamically to meet application needs.

*Cluster Upgrades:* A demonstration of centralized fleet management by exploring cluster upgrade processes, and a walkthrough of the cluster upgrade process using Red Hat Advanced Cluster Management for Kubernetes.


== Version Information

This edition of the lab has been developed using the following software versions:

Red Hat Advanced Cluster Management for Kubernetes 2.12

Red Hat OpenShift 4.17.4

Red Hat OpenShift Virtualization 4.17.1

Red Hat OpenShift Data Foundation 4.16.3

Multicluster Engine for Kubernetes 2.7.1
