== Lab Wrap-up and Summary

In completing this lab you will have performed the following tasks:

*Hosted Cluster Deployment:* 

* We reviewed the prerequisites required to deploy an OpenShift on OpenShift cluster with hosted control planes.
* We made use of Red Hat Advanced Cluster Management for Kubernetes to deploy our OpenShift on OpenShfit cluster.
* We explored our deployed cluster, including the control plane pods and node pools that it is composed of.


*Configuration:* 

* We configured authentication for our cluster from the hosting cluster environment.
* We tested our authentication method, and applied authorization configurations to our hosted cluster environment.


*Scaling:* 

* We deployed an application in our hosted cluster, demonstrating that processes are the same as any other OpenShift deployment.
* We configured our node pools to autoscale when resources are unavaialable to meet application requests.
* We scaled our application up to multiple replicas, triggering an autoscale event.
* We deleted our deployment and observed the cluster autoscale back down once extra resources weren't required.


*Cluster Upgrades:* 

* We explored the different methods available to us to upgrade our hosted cluster, or our entire fleet of clusters.
* We performed a cluster upgrade using Red Hat Advanced Cluster Management for Kubernetes.


